'''SQLAlchemy ORM models for the mock MotionTools database.

Table names, enums, and field shapes mirror the real MotionTools export
data structure (verified against the real CSVs) so that when API access
is granted, the swap from mock -> real is minimal.
'''
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, DateTime, ForeignKey, Text, Boolean, JSON
)
from sqlalchemy.orm import relationship
from app.db.database import Base


# ---------- Enums (kept as string constants for SQLite portability) ----------

BOOKING_STATUSES = (
    'to_be_dispatched',   # created, not yet visible to riders
    'pickable',           # dispatched, visible to riders, unassigned
    'en_route',           # assigned + rider on the way (== 'active')
    'paid',               # completed
    'cancelled',
)

VEHICLE_TYPES = ('bike_regular', 'car_small')

DRIVER_STATUSES = ('available', 'busy', 'offline', 'invited')

RETRY_STATUSES = (
    'none',
    'wait_pending',
    'wait_expired',
    'redispatched',
)


# ---------- Tables ----------

class Driver(Base):
    __tablename__ = 'drivers'

    id = Column(String, primary_key=True)         # UUID from CSV or generated
    email = Column(String, unique=True, index=True, nullable=False)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # Operational fields (not in raw CSV, generated by seeder)
    status = Column(String, default='offline')     # available / busy / offline / invited
    vehicle_type = Column(String, default='bike_regular')
    service_area = Column(String, nullable=True)
    organization = Column(String, nullable=True)
    blocked = Column(Boolean, default=False)

    # Relationships
    bookings = relationship('Booking', back_populates='driver')


class Restaurant(Base):
    __tablename__ = 'restaurants'

    id = Column(String, primary_key=True)
    name = Column(String, nullable=False)
    address = Column(String, nullable=False)
    city = Column(String, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    bookings = relationship('Booking', back_populates='restaurant')


class Booking(Base):
    __tablename__ = 'bookings'

    id = Column(String, primary_key=True)          # UUID (matches MotionTools shape)
    external_id = Column(String, unique=True, index=True, nullable=False)  # 'FFFXTC'-style short ID
    status = Column(String, default='to_be_dispatched')

    # Customer info (denormalized on the booking, as in real export)
    customer_id = Column(String, nullable=True)
    customer_first_name = Column(String, nullable=True)
    customer_last_name = Column(String, nullable=True)
    customer_phone = Column(String, nullable=True)

    # Restaurant (pickup)
    restaurant_id = Column(String, ForeignKey('restaurants.id'), nullable=False)
    pickup_address = Column(String, nullable=False)

    # Drop-off
    dropoff_address = Column(String, nullable=False)

    # Assignment
    driver_id = Column(String, ForeignKey('drivers.id'), nullable=True)

    # Timing
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    scheduled_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Delivery confirmation (per-booking, generated on creation)
    delivery_code = Column(String, nullable=False)   # 4-digit string

    # AI agent retry state (per-booking memory for wait-and-retry flows)
    retry_status = Column(String, default='none')    # RETRY_STATUSES
    retry_started_at = Column(DateTime, nullable=True)
    retry_count = Column(Integer, default=0)

    # Vehicle/capability required
    vehicle_type = Column(String, default='bike_regular')

    # Relationships
    driver = relationship('Driver', back_populates='bookings')
    restaurant = relationship('Restaurant', back_populates='bookings')
    conversations = relationship('Conversation', back_populates='booking')


class Conversation(Base):
    __tablename__ = 'conversations'

    id = Column(String, primary_key=True)
    booking_id = Column(String, ForeignKey('bookings.id'), nullable=False)
    driver_id = Column(String, ForeignKey('drivers.id'), nullable=False)

    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    closed_at = Column(DateTime, nullable=True)
    status = Column(String, default='open')  # open / closed / escalated

    booking = relationship('Booking', back_populates='conversations')
    messages = relationship('ConversationMessage', back_populates='conversation',
                            order_by='ConversationMessage.created_at')


class ConversationMessage(Base):
    __tablename__ = 'conversation_messages'

    id = Column(String, primary_key=True)
    conversation_id = Column(String, ForeignKey('conversations.id'), nullable=False)
    sender = Column(String, nullable=False)   # 'rider' / 'ai' / 'human_agent' / 'system'
    text = Column(Text, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    # For AI messages: what intent was classified, what tools were called
    metadata_json = Column(JSON, nullable=True)

    conversation = relationship('Conversation', back_populates='messages')


class AuditLogEntry(Base):
    '''Row-level unit for Findings-chapter metrics.

    Every agent decision, every tool call, every human intervention lands
    here. Aggregating this table produces automation rate, intent accuracy,
    processing time, escalation rate, etc.
    '''
    __tablename__ = 'audit_log'

    id = Column(String, primary_key=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    booking_id = Column(String, index=True, nullable=True)
    conversation_id = Column(String, index=True, nullable=True)
    driver_id = Column(String, index=True, nullable=True)

    actor = Column(String, nullable=False)   # 'SYSTEM' / 'AI_AGENT' / 'HUMAN_AGENT' / 'RIDER'
    event_type = Column(String, nullable=False)  # 'booking_created', 'intent_classified', 'tool_called', 'escalated', etc.
    description = Column(Text, nullable=False)
    payload_json = Column(JSON, nullable=True)   # structured details for later analysis
